export const APILAYER_BASE_URL = 'https://apilayer.com/';
export const CURRENCY_BASE_URL = 'https://apilayer.com/marketplace/currency_data-api'
export const EXCHANGERATES_BASE_URL = 'https://apilayer.com/marketplace/exchangerates_data-api';
export const FIXER_BASE_URL ='https://apilayer.com/marketplace/fixer-api';
export const IPAPI_BASE_URL = "https://ipapi.com";
export const MARKETSTACK_BASE_URL = "https://marketstack.com/";
export const MEDIASTACK_BASE_URL = "https://mediastack.com/";
export const NUMBERVERIFICATION_BASE_URL = "https://apilayer.com/marketplace/number_verification-api";
export const POSITIONSTACK_BASE_URL = "https://positionstack.com/";
export const TAXDATA_BASE_URL = "https://apilayer.com/marketplace/tax_data-api";
export const ZENSCRAPE_BASE_URL = "https://zenscrape.com/";
export const IPSTACK_BASE_URL = "https://ipstack.com/";